### ISSUE TITLE
How to list tests in multiple files and test everything in one exe

### ISSUE THREAD

**Issue by BrendanSimon** [mity/acutest#11]
How do I list tests in multiple test files and have them aggregated so I can test everything in one executable?

Could you add this to the tutorial or other documentation please.

Thanks :)

**Comment by BrendanSimon** [comment]
Would it be easy to have `TEST_LIST` initialized with a null entry, and then add and API to append to it.  e.g. `TEST_LIST_APPEND()`?

That way each module could just add to the list, without have to create a separate module to list every test in.

Just a thought.

**Comment by mity** [comment]
> Would it be easy to have `TEST_LIST` initialized with a null entry, and then add and API to append to it. e.g. `TEST_LIST_APPEND()`?

In C++, it would be possible. Such registration could be done from some constructor of a global object.

In (portable) C, no, I am afraid. Where could be such API called from? IMHO the only way would be to introduce some callbacks called early from `main()` to observe and register the unit tests, but then you would have the same problem with centralized list of such registering functions.
