### ISSUE TITLE
“Test Anything Protocol” output mode

### ISSUE THREAD

**Issue by sandhose** [mity/acutest#16]
[TAP (Test Anything Protocol)](https://testanything.org/) is a simple text protocol to deal with test results. It should be quite easy to implement, and would make acutest easily integrate with existing tools.

A TAP output looks like this:

```tap
1..4
ok 1 - Input file opened
not ok 2 - First line of the input valid
ok 3 - Read the rest of the file
not ok 4 - Summarized correctly # TODO Not written yet
```

It would enable for example to [produce JUnit XML files](https://www.npmjs.com/package/tap-junit) for the test results and displaying them in [GitLab merge requests](https://docs.gitlab.com/ee/ci/junit_test_reports.html), or to display the [test results in Jenkins](https://wiki.jenkins.io/display/JENKINS/TAP+Plugin) easily

**Comment by mity** [comment]
I have cooked something in PR #17.

Given I do not have any TAP harnessing running anywhere, it would be cool if you could test it before I merge it.

To enable it, use the new `--tap` option.
