### ISSUE TITLE
testsuite name

### ISSUE THREAD

**Issue by mity** [mity/acutest#22]
@AndreRenaud I have just noticed the xUnit XML outputs a hardcoded string ("acutest") as the testsuite name. I am wondering whether it is the right thing to do. 

Consider a larger project which builds multiple test suites, all using acutest. CI or whatever harnessing is there can be confused if it understands all of them as a newer run of the same test suite, and also some summary report could be hard to decode.

Maybe using something more specific, e.g. `argv[0]` (or `basename()` of it, and on Windows without the `.exe` suffix) might be better?

**Comment by AndreRenaud** [comment]
I’m literally half-way through a PR for this now :) I’ll send it shortly.

**Comment by AndreRenaud** [comment]
#23 Should cover this
