### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [mity/acutest#39]
I would like to point out that an identifier like “[`test_list__`](https://github.com/mity/acutest/blob/8881ad41b2ed84c5c3658319ec54b20563fb263c/include/acutest.h#L42 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mity** [comment]
Thanks for pointing it out. I've been aware identifiers cannot begin with `_` but not that double-underscores are reserved too.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/mity/acutest/commit/4864fca6ee67b11cec99edbec76acf5cc07a495c "Renaming of some identifiers").
