### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [mity/acutest#40]
Would you like to [add more error handling](https://github.com/mity/acutest/blob/4864fca6ee67b11cec99edbec76acf5cc07a495c/include/acutest.h#L1638 "Update candidate") for [return values from calls of a function like printf()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output")?

**Comment by mity** [comment]
No. What we should do in a case it fails? Call `printf()` or `fprintf()` to print an error message? It makes no sense.

**Comment by elfring** [comment]
Please [reconsider the possibility](https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors "Detect and handle standard library errors.") to [indicate such a software failure by an other program exit status](https://en.wikipedia.org/wiki/Exit_status "Description for exit code").
