### ISSUE TITLE
Memory leak in children

### ISSUE THREAD

**Issue by dato** [mity/acutest#52]
After fork(), `test_details_` is never free’d, as is is in the parent process.

I use Valgrind with my students projects to detect memory leaks, and the "still unreachable" message, though harmless, confuses them. (The warning does not appear when running with `-E`, of course.)

If nobody beats me to it, in a few days I can send a PR to fix this.

**Comment by mity** [comment]
Thanks for reporting in. 

Got an insomnia today, so should be fixed :-)

**Comment by dato** [comment]
Thank you for fixing it so promptly1
