### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by rittneje** [mity/acutest#68]
I raised issue #62 and PR #63 two months ago, but so far they have been ignored. Is this repo abandoned?

I don't mean to be rude, just want to know if I should directly update the vendored copy instead of fixing the upstream.

**Comment by mkinney** [comment]
What is the location of the "vendored copy"?

**Comment by rittneje** [comment]
As this has not received any response, and this repo has been completely inactive for months, I will assume the answer is "yes".
