### ISSUE TITLE
Any way to figure out code coverage or lines not covered?

### ISSUE THREAD

**Issue by mkinney** [mity/acutest#69]
This is probably a stretch, but is there a way to get code coverage reports? (percentage of lines covered, lines not covered, etc.)

**Comment by mity** [comment]
That's surely beyond what Acutest can reasonably do on its own. With such a low-level programming language as C, you generally cannot do that without compiler support to generate such reports (and possibly other tools to visualize the results in a human readable form).

In a nutshell, build with gcc's options `-g --coverage`, then run the tests, and finally you may use `gcov` or `lcov` or other similar tools to process the collected stats into some human-readable form. I guess MSVC or other compilers can provide similar tools.

If it helps, I'm doing exactly that in CI builds of some of my other projects, so look at their CI build scripts (here the collected stats are uploaded to https://codecov.io/ which is able to visualize the reports nicely):
* [MD4C](https://github.com/mity/md4c/blob/master/.github/workflows/ci-build.yml) (and the [result](https://app.codecov.io/github/mity/md4c))
* [Centijson](https://github.com/mity/centijson/blob/master/.travis.yml) (and the [result](https://app.codecov.io/github/mity/centijson))
