### ISSUE TITLE
Can exception handling be disabled for use in testing embedded C++ systems?

### ISSUE THREAD

**Issue by scottdwhitney** [mity/acutest#72]
Hello, we are trying to do some testing of a resource-constrained C/C++ embedded project, which has exception handling disabled.  However, it seems like acutest is set up to handle testing of exceptions.  Is there a way to configure acutest so that no exception handling or testing is supported for use with embedded systems?  Thank you!

**Comment by mity** [comment]
Sorry for very late answer. 

It should now be possible if you define macro `TEST_NO_EXCEPTIONS` before including `acutest.h`. It even tries to auto-detect when to do that on its own, but it may quite possibly fail with some old/obscure C++ compilers some embedded platforms use. Hopefully at least gcc/clang-based compilers should be fine though.
