### ISSUE TITLE
Multiple definition of `test_check__'

### ISSUE THREAD

**Issue by ema-pe** [mity/acutest#9]
Hi, I'm trying to use this nice library, but I have an issue. It seems that the macros are defined in multiple files, but I don't know exactly, because I'm a C beginner. I'm using this library following this workflow:

- A `main.c` file that contains `TEST_LIST` with all tests;
- A `tests_list.h` file that contains all definition of tests;
- A `test_example.c` file that contains the implementation of a test.

To reproduce the error:
**main.c**

```
#include "acutest.h"

#include "tests_list.h"

TEST_LIST = {
        { "example", test_example },
        { 0 }
};
```

**tests_list.h**

```
#ifndef TESTS_LIST_H
#define TESTS_LIST_H

void test_example(void);

#endif /* TESTS_LIST_H */
```

**test_example.c**

```
#include "acutest.h"

#include <stdlib.h>

void test_example(void)
{
        void* mem;
        int a, b;

        mem = malloc(10);
        TEST_CHECK(mem != NULL);

        mem = realloc(mem, 20);
        TEST_CHECK(mem != NULL);

        a = 1;
        b = 2;
        TEST_CHECK_(a + b == 3, "Expected %d, got %d", 3, a + b);
}
```

Compile with:
`gcc -c test_example.c`
`gcc -c main.c`
`gcc -o example main.o test_example.o`

The output of the last command is:

```
test_example.o: In function `test_check__':
test_example.c:(.text+0x1ba): multiple definition of `test_check__'
main.o:main.c:(.text+0x1ba): first defined here
test_example.o: In function `main':
test_example.c:(.text+0x7e4): multiple definition of `main'
main.o:main.c:(.text+0x7e4): first defined here
collect2: error: ld returned 1 exit status
```

I [asked](https://github.com/nothings/stb/issues/457) to [stb](https://github.com/nothings/stb) repository (because stb project is like this), but I don't understand where is the problem...

**Comment by mity** [comment]
`"acutest.h"` by default defines function `main()` and some other internal things it needs. This is fine as long as there is just one compilation unit which includes it. (And in majority of cases, there is no need to include it in multiple files because test is usually implementation quite short. Even your example separates the test list into extra source for no apparent reason.)

But if you include it in multiple compilation units, it causes multiple definitions of all of those things.

You can still include the header multiple times if all sources but one define the macro `TEST_NO_MAIN` before including `"acutest.h"` to disable (re)definition of `main()` et al.:
```
#define TEST_NO_MAIN
#include "acutest.h"
```

(See also the documentation of the macro in the header file.)

**Comment by ema-pe** [comment]
Thanks for the reply.

> And in majority of cases, there is no need to include it in multiple files because test is usually implementation quite short. Even your example separates the test list into extra source for no apparent reason.

My problem is that I have a library with lots of functions; every function has a test function. To organize the `test` folder, I grouped functions together that have something in common (for example: with functions that perform I/O operations, tests are in `test_functions_io.c`, with functions that handle strings, tests are in `test_functions_strings.c` ettc.).
I have finally one header, in which are listed all tests, and a main `.c` file with `TEST_LIST`.

So to fix the error do I need to define `TEST_NO_MAIN` to all `.c` files except for one?

**Comment by mity** [comment]
Well, you may also reversed logic as well:
 * Add `-DTEST_NO_MAIN` on compiler commnand line to define it everywhere, 
 * and `#undef TEST_NO_MAIN` in one of the sources.

You may also consider building each of the test groups as a standalone program. That gives also an advantage that you can easily run just one group of related tests.

**Comment by ema-pe** [comment]
> You may also consider building each of the sources as a standalone program. That gives you also an advantage that you can easily run just one group of related tests.

That is my current workflow, but I prefer to follow my original idea. Anyway, thanks for the support!
